services:
  - type: web
    name: site-junona
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python create_admin.py && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: site-junona-db
          property: connectionString
    databases:
      - name: site-junona-db
        plan: free

